spring:
  application:
    name: order-processing
    
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  security:
    jwt:
      secret: "zQ0vT9!A@6jX#7wM2*cN$9bV&8lP5sE1yR4uI^3oK"
      expirationMs: 3600000 # 1 Hour

server:
  port: 8080
