spring:
  application:
    name: order-processing
  mvc:
    problemdetails:
      enabled: true
    
  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  security:
    jwt:
      secret: "dGhpcyBpcyBhIHNlY3VyZSBzZWNyZXQga2V5IGZvciBqd3QgdG9rZW4gZ2VuZXJhdGlvbiE="
      expirationMs: 3600000 # 1 Hour

server:
  port: 8080
